config/routes.rb
Rails.application.routes.draw do
	resources :subjects
	resources :suburbs
	resources :localities
	resources :tips
	resources :states
	resources :notifications
	resources :routes
	resources :operators
	resources :suggestions
	resources :garbage_types
	resources :publications
	# rutas para todas las funciones de autenticacion
  devise_for :users, :controllers => { 
		:registrations => "users/registrations",
		:sessions => "users/sessions",
		:confirmations => "users/confirmations",
		:passwords => "users/passwords",
		:unlocks => "users/unlocks",
		:mailer => "users/mailer"
  }

  scope "/admin" do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'welcome#index'
	get '/home', to: 'home#index', as: 'home'
	namespace :api, defaults: { format: 'json' } do
		namespace :v1 do 
			resources :users, only: [:index, :show]
			resources :suggestions
			resources :subjects

			devise_scope :user do
				match '/sessions' => 'sessions#create', via: :post
				match '/sessions' => 'sessions#destroy', via: :delete
			end
		end
	end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.has_role? :admin
        can :assign_roles
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/garbage_type.rb
class GarbageType < ApplicationRecord
	resourcify
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
	resourcify
end

app/models/operator.rb
class Operator < ApplicationRecord
	resourcify
end

app/models/publication.rb
class Publication < ApplicationRecord
	resourcify
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/route.rb
class Route < ApplicationRecord
	resourcify
end

app/models/state.rb
class State < ApplicationRecord
	resourcify
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/suburb.rb
class Suburb < ApplicationRecord
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	resourcify
end

app/models/tip.rb
class Tip < ApplicationRecord
	resourcify
end

app/models/user.rb
class User < ApplicationRecord
	rolify
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :assign_default_role
	
	has_many :suggestions

	def assign_default_role
		if self.id == 1
			add_role(:admin)
		else
			add_role(:normal)
		end
	end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: 'Locality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:name, :city_id, :latitude, :longitude)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/localities/_form.html.erb
<%= form_with(model: locality, local: true) do |form| %>
  <% if locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.number_field :city_id %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', localities_path %>

app/views/localities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= locality.name %></td>
        <td><%= locality.city_id %></td>
        <td><%= locality.latitude %></td>
        <td><%= locality.longitude %></td>
        <td><%= link_to 'Show', locality %></td>
        <td><%= link_to 'Edit', edit_locality_path(locality) %></td>
        <td><%= link_to 'Destroy', locality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locality', new_locality_path %>

app/views/localities/new.html.erb
<h1>New Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Back', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @locality.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @locality.city_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @locality.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @locality.longitude %>
</p>

<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %>