config/routes.rb
Rails.application.routes.draw do
	resources :subjects
	resources :suburbs
	resources :localities
	resources :tips
	resources :states
	resources :notifications
	resources :routes
	resources :operators
	resources :suggestions
	resources :garbage_types
	resources :publications
	# rutas para todas las funciones de autenticacion
  devise_for :users, :controllers => { 
		:registrations => "users/registrations",
		:sessions => "users/sessions",
		:confirmations => "users/confirmations",
		:passwords => "users/passwords",
		:unlocks => "users/unlocks",
		:mailer => "users/mailer"
  }

  scope "/admin" do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'welcome#index'
	get '/home', to: 'home#index', as: 'home'
	namespace :api, defaults: { format: 'json' } do
		namespace :v1 do 
			resources :users, only: [:index, :show]
			resources :suggestions
			resources :subjects

			devise_scope :user do
				match '/sessions' => 'sessions#create', via: :post
				match '/sessions' => 'sessions#destroy', via: :delete
			end
		end
	end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.has_role? :admin
        can :assign_roles
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/garbage_type.rb
class GarbageType < ApplicationRecord
	resourcify
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
	resourcify
end

app/models/operator.rb
class Operator < ApplicationRecord
	resourcify
end

app/models/publication.rb
class Publication < ApplicationRecord
	resourcify
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/route.rb
class Route < ApplicationRecord
	resourcify
end

app/models/state.rb
class State < ApplicationRecord
	resourcify
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/suburb.rb
class Suburb < ApplicationRecord
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	resourcify
end

app/models/tip.rb
class Tip < ApplicationRecord
	resourcify
end

app/models/user.rb
class User < ApplicationRecord
	rolify
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :assign_default_role
	
	has_many :suggestions

	def assign_default_role
		if self.id == 1
			add_role(:admin)
		else
			add_role(:normal)
		end
	end
end

app/controllers/garbage_types_controller.rb
class GarbageTypesController < ApplicationController
  before_action :set_garbage_type, only: [:show, :edit, :update, :destroy]

  # GET /garbage_types
  # GET /garbage_types.json
  def index
    @garbage_types = GarbageType.all
  end

  # GET /garbage_types/1
  # GET /garbage_types/1.json
  def show
  end

  # GET /garbage_types/new
  def new
    @garbage_type = GarbageType.new
  end

  # GET /garbage_types/1/edit
  def edit
  end

  # POST /garbage_types
  # POST /garbage_types.json
  def create
    @garbage_type = GarbageType.new(garbage_type_params)

    respond_to do |format|
      if @garbage_type.save
        format.html { redirect_to @garbage_type, notice: 'Garbage type was successfully created.' }
        format.json { render :show, status: :created, location: @garbage_type }
      else
        format.html { render :new }
        format.json { render json: @garbage_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garbage_types/1
  # PATCH/PUT /garbage_types/1.json
  def update
    respond_to do |format|
      if @garbage_type.update(garbage_type_params)
        format.html { redirect_to @garbage_type, notice: 'Garbage type was successfully updated.' }
        format.json { render :show, status: :ok, location: @garbage_type }
      else
        format.html { render :edit }
        format.json { render json: @garbage_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garbage_types/1
  # DELETE /garbage_types/1.json
  def destroy
    @garbage_type.destroy
    respond_to do |format|
      format.html { redirect_to garbage_types_url, notice: 'Garbage type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garbage_type
      @garbage_type = GarbageType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garbage_type_params
      params.require(:garbage_type).permit(:name, :picture, :description)
    end
end

app/helpers/garbage_types_helper.rb
module GarbageTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/garbage_types/_form.html.erb
<%= form_with(model: garbage_type, local: true) do |form| %>
  <% if garbage_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garbage_type.errors.count, "error") %> prohibited this garbage_type from being saved:</h2>

      <ul>
      <% garbage_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/garbage_types/edit.html.erb
<h1>Editing Garbage Type</h1>

<%= render 'form', garbage_type: @garbage_type %>

<%= link_to 'Show', @garbage_type %> |
<%= link_to 'Back', garbage_types_path %>

app/views/garbage_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Garbage Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garbage_types.each do |garbage_type| %>
      <tr>
        <td><%= garbage_type.name %></td>
        <td><%= garbage_type.picture %></td>
        <td><%= garbage_type.description %></td>
        <td><%= link_to 'Show', garbage_type %></td>
        <td><%= link_to 'Edit', edit_garbage_type_path(garbage_type) %></td>
        <td><%= link_to 'Destroy', garbage_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garbage Type', new_garbage_type_path %>

app/views/garbage_types/new.html.erb
<h1>New Garbage Type</h1>

<%= render 'form', garbage_type: @garbage_type %>

<%= link_to 'Back', garbage_types_path %>

app/views/garbage_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garbage_type.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @garbage_type.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @garbage_type.description %>
</p>

<%= link_to 'Edit', edit_garbage_type_path(@garbage_type) %> |
<%= link_to 'Back', garbage_types_path %>